services:
  - type: web
    name: expense-tracker
    runtime: docker
    plan: free
    envVars:
      - key: MYSQL_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: MYSQL_USER
        fromDatabase:
          name: expense-tracker-db
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: expense-tracker-db
          property: password

databases:
  - name: expense-tracker-db
    plan: free
    databaseName: expense_tracker
    ipAllowList: []
