# TiDB Cloud Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=xdUt6jxjajgeQ1W.root
db.password=7sfWFQSY8BlAeb7z
db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
