# TiDB Cloud Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/expense_tracker?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
db.user=xdUt6jxjajgeQ1W.root
db.password=7sfWFQSY8BlAeb7z
db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
